project_id = "szncoppcatmwyurukpfg"

[functions.generate-sales-text]
verify_jwt = true

[functions.generate-product-ideas]
verify_jwt = false

[functions.eduzz-webhook]
verify_jwt = false

[functions.admin-manage-user]
verify_jwt = false
